###


GET http://localhost:7071/api/collection/Player
###
GET  http://localhost:7071/api/playerTeam/1?key=teamid

###
GET https://kirkitapi.azurewebsites.net/api/references/BallType?code=Dye9kpJckiwh0/fgKtG8wxGNgUAjza9JMEduq0TduuO1fwGkqiKWzQ==
//x-functions-key : NCljoJjVBrNFj4OYMhgyxFyE7gzoBo0/ZfLfmDFMF7LET9ymJnTdUA==


###
POST http://localhost:7071/api/Player

 {
    "FirstName" : "Umesh",
    "LastName" : "Yadav",
    "Email" : "mrahulshakya@g21.com",
    "PhoneNumber" : 7350667661,
    "Age" : 26
  }

###
POST http://localhost:7071/api/collection/PlayerTeam

[
  {
    "TeamId" : 2,
    "PlayerId" : 14,
  },
  {
    "TeamId" : 2,
    "PlayerId" : 15,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 16,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 17,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 18,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 19,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 20,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 21,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 22,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 23,
  },
   {
    "TeamId" : 2,
    "PlayerId" : 24,
  },
]