

GET http://localhost:7071/api/PLayerTeam/22?key=playerId

###
GET http://localhost:7071/api/collection/PLayerTeam

###
POST http://localhost:7071/api/Match
  
{
    "TeamAid" : 2,
    "TeamBid" : 1,
    "IsComplete" : false,
    "DtSchedule" : "2018-05-31T16:03:20.615Z"
}

###
POST http://localhost:7071/api/TotalScore

{
    "TotalRuns" : 0,
    "InningsId" : 1,
    "TotalOvers" : 0,
    "TotalBalls" : 0,
    "TotalWickets" : 0,
    "ExtraRuns" : 0
}

###
GET http://localhost:7071/api/TotalScore/1?key="InningsId"

###
POST http://localhost:7071/api/Innings

{
  "Name" : "India batting innings",
  "MatchId" :  1,
  "BattingTeamId" : 2,
  "BowlingTeamId" : 1,
  "PlayeOnStrikeId"  : 6,
  "PlayerOnNonStrikeId"  :5,
  "BallerId" : 21,
 }